log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    - certFile: "/certs/rest-service.crt"
      keyFile: "/certs/rest-service.key"
